insert into public.agenda_import_staging (
  import_batch,
  source_kind,
  source_label,
  user_name,
  team_name,
  entry_date,
  start_time,
  end_time,
  title,
  project_name,
  client_name,
  category_label,
  notes,
  needs_review,
  review_reason
)
values
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-06',
    time '10:00',
    null,
    'Verifier si c''est mon tour de menage',
    null,
    null,
    null,
    'Lecture depuis capture agenda. Bloc visible mais heure de fin non lisible.',
    true,
    'Heure de fin non lisible'
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-07',
    time '10:00',
    time '12:15',
    'Reunion Boussole',
    'Cargonautes',
    'Cargonautes',
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-07',
    time '14:30',
    time '16:00',
    'Audition ADEME 14h45',
    null,
    null,
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-07',
    time '16:00',
    null,
    'Claire / Paulo',
    'Cargonautes',
    'Cargonautes',
    null,
    'Lecture depuis capture agenda. Bloc visible mais heure de fin non lisible.',
    true,
    'Heure de fin non lisible'
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-07',
    time '17:00',
    time '20:00',
    'Shift coursier',
    null,
    null,
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-08',
    time '12:30',
    time '15:00',
    'Entretien d''evolution Claire',
    null,
    null,
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-08',
    time '18:00',
    time '20:00',
    'Coucou',
    null,
    null,
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-09',
    time '10:00',
    time '11:15',
    'Cercle management',
    null,
    null,
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-09',
    time '13:00',
    time '14:30',
    'BaV | F Bureau',
    null,
    'Microsoft Teams',
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-09',
    time '18:30',
    time '20:30',
    'Reunion d''equipe',
    'Cargonautes',
    'Cargonautes',
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-10',
    time '09:00',
    time '15:00',
    'Moment de concentration',
    null,
    null,
    null,
    'Lecture depuis capture agenda.',
    false,
    null
  ),
  (
    'paulo-week-2026-04-06',
    'calendar_capture',
    'Capture agenda Paulo semaine 2026-04-06',
    'Paulo',
    'Conseil Operations France',
    date '2026-04-10',
    time '11:00',
    null,
    'Cargonautes / synthese compta',
    'Cargonautes',
    'Microsoft Teams',
    null,
    'Lecture depuis capture agenda. Bloc visible mais heure de fin non lisible.',
    true,
    'Heure de fin non lisible'
  );
